# IDE things
[[plugins]]
repo = 'justinmk/vim-dirvish'
[[plugins]]
repo = 'kristijanhusak/vim-dirvish-git'
[[plugins]]
repo = 'jwilm/i3-vim-focus'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'sirver/ultisnips'
[[plugins]]
repo = 'ervandew/supertab'
[[plugins]]
repo = 'terryma/vim-multiple-cursors'
[[plugins]]
repo = 'Yggdroot/indentLine'
[[plugins]]
repo = 'benmills/vimux'
[[plugins]]
repo = 'kien/ctrlp.vim'
[[plugins]]
repo = 'tpope/vim-vinegar'
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
[[plugins]]
repo = 'xolox/vim-session'
[[plugins]]
repo = 'xolox/vim-misc'
[[plugins]]
repo = 'junegunn/goyo.vim'
[[plugins]]
repo = 'junegunn/limelight.vim'
[[plugins]]
repo = 'wsdjeg/vim-todo'
[[plugins]]
repo = 'tpope/vim-surround'

# Autocompletion
[[plugins]]
repo = 'ncm2/ncm2'
[[plugins]]
repo = 'ncm2/ncm2-ultisnips'
[[plugins]]
repo = 'ncm2/ncm2-path'
[[plugins]]
repo = 'ncm2/ncm2-tmux'
[[plugins]]
repo = 'ncm2/ncm2-bufword'
[[plugins]]
repo = 'ncm2/ncm2-vim'
[[plugins]]
repo = 'ncm2/ncm2-jedi'
on_ft = ['py','python']
[[plugins]]
repo = 'ncm2/ncm2-pyclang'
on_ft = ['c','cpp','c++','h']

# helpers
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
[[plugins]]
repo = 'jiangmiao/auto-pairs'
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
[[plugins]]
repo = 'w0rp/ale'

# styling
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'srcery-colors/srcery-vim'

# languane plugins
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
build = ':GoInstallBinaries'
[[plugins]]
repo = 'nsf/gocode'
on_ft = 'go'
build = '~/.vim/dein/repos/github.com/nsf/gocode/vim/symlink.sh'
rtp = 'vim'
[[plugins]]
repo = 'benmills/vimux-golang'
on_ft = 'go'
[[plugins]]
repo = 'buoto/gotests-vim'
on_ft = 'go'
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rs', 'rust']
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'js'
[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'htm']
[[plugins]]
repo = 'suoto/vim-hdl'
on_ft = ['hdl','vhdl']
[[plugins]]
repo = 'ledger/vim-ledger'
on_ft = 'ledger'
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex','latex']
[[plugins]]
repo = 'KeitaNakamura/tex-conceal.vim'
on_ft = ['tex','latex']
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
