[theme]
name = "bad-wolf"
[theme.overrides]

[icons]
name = "none"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "

[[block]]
block = "custom"
command = "i3-gnome-pomodoro status"
on_click = "i3-gnome-pomodoro toggle"
interval = 1

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlp58s0"
ssid = true
ip = true
bitrate = false
speed_up = false
graph_up = false
speed_down = false
graph_down = false
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/ "
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
interval = 5

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "load"
interval = 10
format = "{1m} {5m}"

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %H:%M"

